version: '3.7'

services:
  web:
    build:
      context: ../mysite
      dockerfile: Dockerfile
    command: gunicorn mysite.wsgi:application --bind 0.0.0.0:8000

    expose:
      - 8000
    env_file:
      - ./.env.prod

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/djangoapp/static
      - media_volume:/djangoapp/media
    ports:
      - 80:80
    depends_on:
      - web

volumes:
  static_volume:
  media_volume:
